config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  
  get 'users/index'
  root to: "users#index"

  post "/export_user" => "users#export"
  get "/export_status" => "users#export_status"
  get "/export_download" => "users#export_download"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def export
    @jid = ExportUserJob.perform_async
    respond_to do |format|
      format.turbo_stream
    end
  end

  def export_download
    job_id = params[:id]
    exported_file_name = "users_export_#{job_id}.xlsx"
    filename = "UserData_#{DateTime.now.strftime("%Y%m%d_%H%M%S")}.xlsx"

    respond_to do |format|
      format.xlsx do
        send_file Rails.root.join("tmp", exported_file_name), type: :xlsx, filename: filename
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleAsyncDownload</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="w-full h-full p-4 m-8 overflow-y-auto">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_blob_progress.html.erb
<div id="<%= jid %>" class="bg-indigo-7 min-height-100" style="width: <%= progress %>%" ></div>

app/views/users/export.turbo_stream.erb
<%= turbo_stream.replace "export" do %>
  <%= turbo_stream_from @jid %>
  <div data-controller="export-user" class="margin-y-2">
    <button class="btn btn--primary" data-action="click->export-user#export">Export</button>
    <div class="width-75 margin-y-2" data-export-user-target="progressWrapper">
      <p class="margin-bottom-2 font-size-1">Processing file</p>
      <div class="border-radius-2 bg-gray-2" style="height: 12px; overflow: hidden;">
        <%= render partial: "blob_progress", locals: { jid: @jid, progress: 0 } %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="width-75 margin-x-auto margin-top-6">
  <h3>Export users</h3>
  <%= turbo_frame_tag "export" do %>
    <%= form_with url: export_user_path do %>
      <div data-controller="export-user" class="margin-y-2">
        <button class="btn btn--primary" data-action="click->export-user#export">Export</button>
        <div class="display-none width-75 margin-y-2" data-export-user-target="progressWrapper">
          <p class="margin-bottom-2 font-size-1">Processing file</p>
          <div class="border-radius-2 bg-gray-2" style="height: 12px; overflow: hidden;">
            <div class="bg-indigo-7 min-height-100" data-export-user-target="progress" style="width: 0%;"></div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>